### PR TITLE
`projectegg` is deprecated in djangorecipe 2.0 (fixes failing buildout)

### PR DESCRIPTION
**Pull request by willbarton**
This PR removes the projectegg line from buildout.cfg. This was causing buildout to fail (for anyone building regulations-core and for Travis here and in regulations-site).

Sibling to cfpb/regulations-site#728

### CODE REVIEW

**Comment by willbarton** [comment]
It's failing on unittests that use but don't configure elasticsearch... for some reason. I'll dig into it, but I don't think this should hold up the fix for regulations-site.

**Comment by ascott1** [comment]
Ok, I'm going to merge the regulations-site PR while we get this sorted out.

**Comment by willbarton** [comment]
Actually, cfpb/regulations-site#728 is still going to fail, but it's still going to fail on the regulations-core component.

**Comment by ascott1** [comment]
Exactly. I'm going to merge that one, since we can see in the travis logs that everything is ok with that repo. When you have some time, let's figure out what's wrong here, but I don't think it's a pressing issue.

**Comment by willbarton** [comment]
@ascott1 Quick, before Travis changes its mind!

**Comment by ascott1** [comment]
YAY!

**Pull request merged**
